# Generated by Django 4.2.27 on 2026-03-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_code', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_telnumber', models.CharField(max_length=50)),
                ('customer_delivery', models.CharField(max_length=50)),
                ('customer_deliveryaddress', models.CharField(max_length=100)),
                ('customer_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_code', models.CharField(max_length=10)),
                ('employee_retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_no', models.CharField(max_length=10)),
                ('instructions_deadline', models.DateField()),
                ('instructions_quantity', models.IntegerField()),
                ('instructions_note', models.TextField()),
                ('instructions_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('item_deleted', models.BooleanField(default=False)),
                ('item_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('order_no', models.CharField(max_length=50)),
                ('order_provisional', models.BooleanField(default=False)),
                ('order_deadline', models.DateField()),
                ('order_note', models.TextField()),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50)),
                ('process_sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionprocess_turn', models.IntegerField()),
                ('productionprocess_instructions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.instructions')),
                ('productionprocess_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.process')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateField()),
                ('shipping_quantity', models.IntegerField()),
                ('shipping_type', models.CharField(choices=[['complete', '完納'], ['partial', '分納'], ['discontinued', '打切']], max_length=20)),
                ('shipping_note', models.TextField()),
                ('shipping_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField()),
                ('progress_quantity', models.IntegerField()),
                ('progress_note', models.TextField()),
                ('progress_defective', models.BooleanField(default=False)),
                ('progress_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee')),
                ('progress_productionprocess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.productionprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemprocess_turn', models.IntegerField()),
                ('itemprocess_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item')),
                ('itemprocess_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.process')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_process',
            field=models.ManyToManyField(through='myapp.ItemProcess', to='myapp.process'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='instructions_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_quantity', models.IntegerField()),
                ('allocation_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.order')),
                ('allocation_progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.progress')),
            ],
        ),
    ]
