# Generated by Django 4.2.27 on 2026-03-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='得意先名')),
                ('customer_code', models.CharField(max_length=50, verbose_name='得意先コード')),
                ('customer_address', models.CharField(default='', max_length=100, verbose_name='得意先住所')),
                ('customer_telnumber', models.CharField(default='', max_length=50, verbose_name='電話番号')),
                ('customer_delivery', models.CharField(default='', max_length=50, verbose_name='納入先名')),
                ('customer_deliveryaddress', models.CharField(default='', max_length=100, verbose_name='納入先住所')),
                ('customer_note', models.TextField(default='', verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='社員名')),
                ('employee_code', models.CharField(max_length=10, verbose_name='社員コード')),
                ('employee_retired', models.BooleanField(default=False, verbose_name='退職')),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_no', models.CharField(max_length=10, verbose_name='生産No')),
                ('instructions_deadline', models.DateField(blank=True, null=True, verbose_name='生産納期')),
                ('instructions_quantity', models.IntegerField(blank=True, null=True, verbose_name='生産数')),
                ('instructions_note', models.TextField(default='', verbose_name='備考')),
                ('instructions_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee', verbose_name='生産担当者')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50, verbose_name='品番')),
                ('item_name', models.CharField(default='', max_length=50, verbose_name='品名')),
                ('item_price', models.IntegerField(blank=True, null=True, verbose_name='単価')),
                ('item_deleted', models.BooleanField(default=False, verbose_name='廃番')),
                ('item_note', models.TextField(default='', verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(blank=True, null=True, verbose_name='受注単価')),
                ('order_quantity', models.IntegerField(blank=True, null=True, verbose_name='受注数')),
                ('order_no', models.CharField(default='', max_length=50, verbose_name='受注番号')),
                ('order_provisional', models.BooleanField(default=False, verbose_name='仮受注')),
                ('order_deadline', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('order_note', models.TextField(default='', verbose_name='備考')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer', verbose_name='得意先')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item', verbose_name='品番')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50, verbose_name='工程名')),
                ('process_sort', models.IntegerField(verbose_name='順番')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionprocess_turn', models.IntegerField(verbose_name='順番')),
                ('productionprocess_instructions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.instructions', verbose_name='生産指示')),
                ('productionprocess_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.process', verbose_name='工程')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='出荷日')),
                ('shipping_quantity', models.IntegerField(blank=True, null=True, verbose_name='出荷数')),
                ('shipping_type', models.CharField(choices=[['complete', '完納'], ['partial', '分納'], ['discontinued', '打切']], default='', max_length=20, verbose_name='出荷区分')),
                ('shipping_note', models.TextField(default='', verbose_name='備考')),
                ('shipping_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee', verbose_name='出荷担当者')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.order', verbose_name='受注')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(verbose_name='作業日')),
                ('progress_quantity', models.IntegerField(verbose_name='数量')),
                ('progress_note', models.TextField(default='', verbose_name='備考')),
                ('progress_defective', models.BooleanField(default=False, verbose_name='不良')),
                ('progress_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee', verbose_name='作業者')),
                ('progress_productionprocess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.productionprocess', verbose_name='生産工程')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemprocess_turn', models.IntegerField(verbose_name='順番')),
                ('itemprocess_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item', verbose_name='品番')),
                ('itemprocess_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.process', verbose_name='工程')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_process',
            field=models.ManyToManyField(through='myapp.ItemProcess', to='myapp.process', verbose_name='標準実施工程'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='instructions_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.item', verbose_name='品番'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_quantity', models.IntegerField(verbose_name='引当数')),
                ('allocation_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.order', verbose_name='受注')),
                ('allocation_progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.progress', verbose_name='進捗')),
            ],
        ),
    ]
