# Generated by Django 4.2.27 on 2026-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_order',
            field=models.BooleanField(default=False),
        ),
    ]
