# Generated by Django 4.2.27 on 2026-02-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_shipping_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
