# Generated by Django 4.2.27 on 2026-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='process_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
