# Generated by Django 4.2.27 on 2026-03-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_item_process_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='process_list',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ItemProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_turn', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.process')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_process',
            field=models.ManyToManyField(through='myapp.ItemProcess', to='myapp.process'),
        ),
    ]
