# Generated by Django 4.2.27 on 2026-03-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_item_id_remove_item_process_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_turn', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.process')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_process',
            field=models.ManyToManyField(through='myapp.OrderProcess', to='myapp.process'),
        ),
    ]
