# Generated by Django 4.2.27 on 2026-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_order_id_alter_order_order_no_orderprocess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_number', models.IntegerField()),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
    ]
