# Generated by Django 4.2.27 on 2026-03-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_order_item_order_item_name_order_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_no',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
            preserve_default=False,
        ),
    ]
